---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-system
        enabled: true
        k8s:
          service:
            ports:
            # Defaults (https://github.com/istio/istio/blob/1.7.0/manifests/charts/gateways/istio-ingress/values.yaml)
            - port: 15021
              targetPort: 15021
              name: status-port
            - port: 80
              targetPort: 8080
              name: http2
            - port: 443
              targetPort: 8443
              name: https
            - port: 15443
              targetPort: 15443
              name: tls
            # Custom
            - port: 12345
              name: grpc-magiconion
            - port: 5432
              name: http-swagger
